
name: Update Labels
on:
  pull_request:
    branches: [ main ]
    types: [closed]

    
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
    - name: Install dependencies
      run: yarn add -D @azu/github-label-setup
    - name: update label
      run: yarn github-label-setup --token ${{ secrets.GITHUB_TOKEN }} --labels .github/labels.json
